upstream {{ forward_upstream_name }} {
  zone {{ forward_upstream_name }} 128k;
{% if upstream_servers.size > 0 %}
{% if lb_method == "least_conn" %}  least_conn;
{% elsif lb_method == "ip_hash" %}  ip_hash;
{% endif %}
{% for server in upstream_servers %}  server {{ server.host }}:{{ server.port }} resolve{% if server.weight > 1 %} weight={{ server.weight }}{% endif %} max_fails={{ server.max_fails }} fail_timeout={{ server.fail_timeout }}{% if server.backup %} backup{% endif %}{% if server.down %} down{% endif %};
{% endfor %}
{% else %}
  server {{ forward_host }}{% if forward_port != null %}:{{ forward_port }}{% endif %} resolve;
{% endif %}
}
